export const CLOVER_STATEMENT_RAW_CODES = {
  FEES_TOTAL: 'CLOVER_FEES_TOTAL',
  MONTHLY_EQUIPMENT_BILL: 'CLOVER_MONTHLY_EQUIPMENT_BILL',
  MONTHLY_EQUIPMENT_BILL_HST: 'CLOVER_MONTHLY_EQUIPMENT_BILL_HST',
  NETWORK_FEES: 'CLOVER_NETWORK_FEES',
  NETWORK_FEES_HST: 'CLOVER_NETWORK_FEES_HST',
  UNCLASSIFIED_FEES: 'CLOVER_UNCLASSIFIED_FEES',
} as const;

export const CLOVER_MONTHLY_EQUIPMENT_CATEGORY_STABLE_ID = 'expense_software';
