export const FANTUAN_ADJUSTMENT_DETAIL_EVIDENCE_KIND =
  'FANTUAN_SETTLEMENT_ADJUSTMENT_DETAIL';

export const FANTUAN_ADJUSTMENT_RAW_CODES = {
  COMPENSATION: 'FANTUAN_ADJUSTMENT_COMPENSATION',
  DEDUCTION: 'FANTUAN_ADJUSTMENT_DEDUCTION',
  UNKNOWN: 'FANTUAN_ADJUSTMENT_UNKNOWN',
} as const;

export const FANTUAN_ADJUSTMENT_SUPPORTED_RAW_CODES = new Set<string>([
  FANTUAN_ADJUSTMENT_RAW_CODES.COMPENSATION,
  FANTUAN_ADJUSTMENT_RAW_CODES.DEDUCTION,
]);
