export const CLOVER_SALES_REPORT_EVIDENCE_KIND = 'CLOVER_SALES_REPORT';

export const CLOVER_SALES_REPORT_RAW_CODES = {
  GROSS_SALES: 'CLOVER_SALES_REPORT_GROSS_SALES',
  REFUNDS: 'CLOVER_SALES_REPORT_REFUNDS',
  NET_SALES: 'CLOVER_SALES_REPORT_NET_SALES',
  TAXES: 'CLOVER_SALES_REPORT_TAXES',
  TIPS: 'CLOVER_SALES_REPORT_TIPS',
  SURCHARGES: 'CLOVER_SALES_REPORT_SURCHARGES',
  AMOUNT_COLLECTED: 'CLOVER_SALES_REPORT_AMOUNT_COLLECTED',
} as const;
