export const CLOVER_STATEMENT_RAW_CODES = {
  // Historical v7 facts remain readable after the modern-statement parser cutover.
  FEES_TOTAL: 'CLOVER_FEES_TOTAL',
  MONTHLY_EQUIPMENT_BILL: 'CLOVER_MONTHLY_EQUIPMENT_BILL',
  MONTHLY_EQUIPMENT_BILL_HST: 'CLOVER_MONTHLY_EQUIPMENT_BILL_HST',

  ACCOUNT_AMOUNT_SUBMITTED: 'CLOVER_ACCOUNT_AMOUNT_SUBMITTED',
  ACCOUNT_PAID_BY_OTHERS: 'CLOVER_ACCOUNT_PAID_BY_OTHERS',
  ACCOUNT_DISPUTES: 'CLOVER_ACCOUNT_DISPUTES',
  ACCOUNT_ADJUSTMENTS: 'CLOVER_ACCOUNT_ADJUSTMENTS',
  ACCOUNT_FEES_TOTAL: 'CLOVER_ACCOUNT_FEES_TOTAL',
  ACCOUNT_AMOUNT_PROCESSED: 'CLOVER_ACCOUNT_AMOUNT_PROCESSED',
  FEE_SUMMARY_FEES: 'CLOVER_FEE_SUMMARY_FEES',
  FEE_SUMMARY_ICPF: 'CLOVER_FEE_SUMMARY_ICPF',
  SERVICE_CHARGES_TOTAL: 'CLOVER_SERVICE_CHARGES_TOTAL',
  SERVICE_CHARGES: 'CLOVER_SERVICE_CHARGES',
  SERVICE_CHARGES_HST: 'CLOVER_SERVICE_CHARGES_HST',
  EQUIPMENT_FEE: 'CLOVER_EQUIPMENT_FEE',
  EQUIPMENT_FEE_HST: 'CLOVER_EQUIPMENT_FEE_HST',
  NETWORK_FEES: 'CLOVER_NETWORK_FEES',
  NETWORK_FEES_HST: 'CLOVER_NETWORK_FEES_HST',
  CARD_PROCESSING_TOTAL_FEES: 'CLOVER_CARD_PROCESSING_TOTAL_FEES',
  UNCLASSIFIED_FEES: 'CLOVER_UNCLASSIFIED_FEES',
  UNCLASSIFIED_SERVICE_CHARGES: 'CLOVER_UNCLASSIFIED_SERVICE_CHARGES',
} as const;

export const CLOVER_EQUIPMENT_CATEGORY_STABLE_ID = 'expense_software';
export const CLOVER_MONTHLY_EQUIPMENT_CATEGORY_STABLE_ID =
  CLOVER_EQUIPMENT_CATEGORY_STABLE_ID;
