export type ContractDomain =
  | 'merchant'
  | 'webhook-receive'
  | 'webhook-worker'
  | 'orders'
  | 'menu'
  | 'operations';

/** Columns: scenario, input, API, persistence, Uber calls, response, idempotency, log deny-list. */
export type UberAcceptanceContract = readonly [
  scenario: string,
  input: string,
  apiStatus: number | 'not-applicable',
  persistence: string,
  uberRequests: number | 'at-most-once' | 'until-confirmed',
  response: string,
  idempotency: string,
  forbiddenLogFields: readonly string[],
];

const secrets = ['access_token', 'refresh_token', 'authorization', 'customer'];

export const acceptanceMatrix: Record<
  ContractDomain,
  readonly UberAcceptanceContract[]
> = {
  merchant: [
    [
      'oauth-state-created',
      'oauth-callback.json',
      200,
      'state=ISSUED',
      0,
      'authorize URL + opaque state',
      'not-consumed',
      [...secrets, 'code', 'state'],
    ],
    [
      'oauth-state-consumed',
      'oauth-callback.json',
      200,
      'state=CONSUMED; connection=UPSERTED',
      1,
      'callback success',
      'one successful consumer',
      [...secrets, 'code', 'state'],
    ],
    [
      'oauth-state-expired',
      'expired signed state',
      401,
      'state remains unconsumed then expires',
      0,
      'authorization rejected',
      'same rejection on retry',
      [...secrets, 'state'],
    ],
    [
      'oauth-session-mismatch',
      'state + another admin session',
      401,
      'state remains unconsumed',
      0,
      'authorization rejected',
      'original session may still consume',
      [...secrets, 'state', 'sessionId'],
    ],
    [
      'oauth-duplicate-callback',
      'same callback twice',
      409,
      'single CONSUMED transition',
      1,
      'second callback rejected',
      'first result wins',
      [...secrets, 'code', 'state'],
    ],
  ],
  'webhook-receive': [
    [
      'invalid-signature',
      'webhook-order.json + invalid signature',
      401,
      'no inbox row',
      0,
      'rejected',
      'non-2xx asks Uber to redeliver; nothing was persisted',
      [...secrets, 'x-uber-signature'],
    ],
    [
      'invalid-envelope',
      'signed invalid JSON or envelope',
      400,
      'no inbox row',
      0,
      'rejected before durable ownership',
      'non-2xx asks Uber to redeliver; nothing was persisted',
      [...secrets, 'x-uber-signature'],
    ],
    [
      'atomic-inbox-commit',
      'signed valid envelope',
      200,
      'inbox=PENDING committed before response',
      0,
      'acknowledged only after commit',
      'internal worker now owns every retry',
      [...secrets, 'x-uber-signature'],
    ],
    [
      'inbox-write-failure',
      'signed valid envelope; database unavailable',
      503,
      'no committed inbox row',
      0,
      'not acknowledged',
      'non-2xx asks Uber to redeliver because ownership was not acquired',
      [...secrets, 'x-uber-signature'],
    ],
    [
      'duplicate-event-id',
      'webhook-order.json twice',
      200,
      'one committed inbox row; worker processes once',
      0,
      'acknowledged',
      'duplicate is safely acknowledged; no external retry requested',
      [...secrets, 'x-uber-signature'],
    ],
    [
      'content-hash-dedup',
      'event without event_id twice',
      200,
      'one inbox row keyed by body hash',
      0,
      'acknowledged',
      'duplicate is safely acknowledged; no external retry requested',
      [...secrets, 'x-uber-signature'],
    ],
  ],
  'webhook-worker': [
    [
      'handler-timeout',
      'signed event; downstream timeout',
      'not-applicable',
      'inbox=FAILED_RETRYABLE',
      0,
      'original HTTP response remains 200',
      'internal inbox retry only; never request Uber redelivery',
      [...secrets, 'x-uber-signature'],
    ],
    [
      'invalid-business-payload',
      'committed envelope with malformed business payload',
      'not-applicable',
      'inbox=FAILED_TERMINAL',
      0,
      'original HTTP response remains 200',
      'terminal failure; Uber redelivery cannot repair persisted bytes',
      [...secrets, 'x-uber-signature'],
    ],
    [
      'unsupported-event',
      'committed unknown event type',
      'not-applicable',
      'inbox=UNSUPPORTED (quarantined)',
      0,
      'original HTTP response remains 200',
      'operator replay after support is added; no Uber redelivery',
      [...secrets, 'x-uber-signature'],
    ],
    [
      'retry-exhausted',
      'retryable handler failure reaches attempt limit',
      'not-applicable',
      'inbox=DEAD after internal retries',
      0,
      'original HTTP response remains 200',
      'operator recovery from durable inbox; no Uber redelivery',
      [...secrets, 'x-uber-signature'],
    ],
  ],
  orders: [
    [
      'new-order',
      'order-notification.json',
      200,
      'order + items + modifiers atomically created',
      1,
      'imported',
      'external order id unique',
      secrets,
    ],
    [
      'duplicate-notification',
      'order-notification.json twice',
      200,
      'single order and payment',
      1,
      'existing result',
      'no duplicate print/event',
      secrets,
    ],
    [
      'amount-mismatch',
      'order total differs from calculated total',
      422,
      'rejected snapshot retained',
      0,
      'validation failure',
      'same failure',
      secrets,
    ],
    [
      'unknown-item-or-modifier',
      'unknown external resource id',
      422,
      'rejected snapshot retained',
      0,
      'validation failure',
      'same failure',
      secrets,
    ],
    [
      'auto-accept-failure',
      'valid order; Uber 503',
      503,
      'order=PAID; ACCEPT outbox=RETRYABLE',
      1,
      'retry requested',
      'one pending ACCEPT',
      secrets,
    ],
    ...(['ACCEPT', 'DENY', 'READY_FOR_PICKUP'] as const).flatMap(
      (action) =>
        [
          [
            action.toLowerCase() + '-idempotent',
            `${action} twice`,
            200,
            `one terminal ${action} result`,
            1,
            'same result',
            'Uber called once',
            secrets,
          ],
          [
            action.toLowerCase() + '-concurrent',
            `two concurrent ${action} commands`,
            200,
            `single claimed ${action} action`,
            'at-most-once',
            'same eventual result',
            'one winner; one duplicate',
            secrets,
          ],
        ] as UberAcceptanceContract[],
    ),
  ],
  menu: [
    [
      'dry-run',
      'menu-nested-modifiers.json',
      200,
      'draft unchanged; audit recorded',
      0,
      'diff + validation report',
      'repeatable',
      secrets,
    ],
    [
      'graph-validation',
      'dangling or cyclic graph',
      422,
      'no publish attempt',
      0,
      'graph errors',
      'repeatable',
      secrets,
    ],
    [
      'nested-modifier-flattening',
      'menu-nested-modifiers.json',
      200,
      'draft unchanged',
      0,
      'deterministic Cartesian products',
      'stable generated ids',
      secrets,
    ],
    [
      'publish-success',
      'confirmed valid dry-run',
      200,
      'publish=SUCCEEDED; version active',
      1,
      'Uber success',
      'same version not republished',
      secrets,
    ],
    [
      'publish-failure',
      'confirmed publish; Uber 4xx',
      422,
      'publish=FAILED; prior version active',
      1,
      'sanitized failure',
      'same attempt remains failed',
      secrets,
    ],
    [
      'publish-confirm-timeout',
      'submitted publish without confirmation',
      504,
      'publish=TIMED_OUT; prior version active',
      'until-confirmed',
      'timeout',
      'polling does not upload again',
      secrets,
    ],
  ],
  operations: [
    [
      'store-provision',
      'store-operation.json',
      200,
      'store=PROVISIONED',
      1,
      'provisioned',
      'already provisioned is a no-op',
      secrets,
    ],
    [
      'store-deprovision',
      'store-operation.json',
      200,
      'store=DEPROVISIONED',
      1,
      'deprovisioned',
      'already deprovisioned is a no-op',
      secrets,
    ],
    [
      'store-status-sync',
      'store-operation.json',
      200,
      'remote status snapshot updated',
      1,
      'sync result',
      'one snapshot per observation',
      secrets,
    ],
    [
      'reconciliation',
      'bounded date range',
      200,
      'report + discrepancies saved',
      1,
      'totals + discrepancies',
      'same range has stable key',
      secrets,
    ],
    [
      'ticket-retry',
      'retryable open ticket',
      200,
      'attempt incremented; resolved or rescheduled',
      1,
      'retry result',
      'one active claim',
      secrets,
    ],
  ],
};
