name: Sync main -> dev

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  open-sync-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write         # 允许推送/读写仓库
      pull-requests: write    # 允许创建/更新 PR
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0      # 建议拉全历史，PR 基线更可靠

      - name: Open/Update PR main -> dev
        uses: repo-sync/pull-request@v2
        with:
          source_branch: main
          destination_branch: dev
          pr_title: "Sync main → dev"
          pr_body: "Automated PR to keep dev up-to-date with main."
          pr_label: "auto-sync"
          github_token: ${{ secrets.GITHUB_TOKEN }}
