name: Sync main -> dev
on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  open-sync-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 先尝试无冲突快进 dev（可选；dev 受保护时会跳过）
      - name: Try fast-forward dev
        id: ff
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin dev
          git checkout -B dev origin/dev
          if git merge --ff-only origin/main; then
            # 若 dev 未受保护可直接推送；受保护时这里会失败，下面会走 PR
            git push origin dev
            echo "result=ff-ok" >> $GITHUB_OUTPUT
          else
            echo "result=need-pr" >> $GITHUB_OUTPUT
          fi

      # 快进失败或 dev 受保护 -> 发 PR
      - name: Create / Update PR main -> dev
        if: steps.ff.outputs.result != 'ff-ok'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ github.token }}
          title: "Sync main → dev"
          body: "Automated PR to sync **main** into **dev**."
          base: dev
          head: main
          draft: false
          labels: sync
